---
# tasks file for rstudio
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: install dep pkgs
  become: yes
  become_user: root
  with_items: '{{rstudio_server_deps|default([])}}'
  package:
    name: '{{item}}'
    state: present
    
- name: download pkg...
  become: yes
  become_user: root
  get_url:
    url: '{{rstudio_server_pkg_url}}'
    dest: /tmp/{{rstudio_pkg}}
    mode: 0644

- include: '{{rstudio_installer|default("package")}}.yml'
